/**
 * 项目名称: ApiUsage
 * 文件名称: CommonConstants
 * 创建时间: 2026-08-13 22:37
 * 创建人：  @author Ffffei
 * 文件描述: TODO
 */

export class CommonConstants{




  public static NAVIGATION_HEIGHT: number = 56;
  public static TAB_BAR_HEIGHT: number = 56;
  // Percent
  public static readonly FULL_PERCENT: string = '100%';
  public static readonly HALF_PERCENT: string = '50%';
  public static readonly AUTO_FIT: string = 'auto';
  // Space
  public static readonly SPACE_2: number = 2;
  public static readonly SPACE_4: number = 4;
  public static readonly SPACE_6: number = 6;
  public static readonly SPACE_8: number = 8;
  public static readonly SPACE_10: number = 10;
  public static readonly SPACE_12: number = 12;
  public static readonly SPACE_14: number = 14;
  public static readonly SPACE_16: number = 16;
  public static readonly SPACE_24: number = 24;
  public static readonly SPACE_28: number = 28;
  public static readonly SPACE_32: number = 32;
  public static readonly SPACE_40: number = 40;
  public static readonly SPACE_48: number = 48;
}